"""empty message

Revision ID: 166af34d5131
Revises: 4ae09d68cc8d
Create Date: 2023-04-17 01:12:52.010704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166af34d5131'
down_revision = '4ae09d68cc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fav_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('fav_id')
        batch_op.drop_column('fav')

    # ### end Alembic commands ###
