"""empty message

Revision ID: 31ad8d20bbfa
Revises: 166af34d5131
Create Date: 2023-04-17 01:33:42.044957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ad8d20bbfa'
down_revision = '166af34d5131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=120), nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
